hotelViz/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^viz/', include('viz.urls', namespace ="viz" )),
    url(r'^admin/', include(admin.site.urls)),
]

viz/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='index'),
    url(r'^explore/', views.ExploreView.as_view(), name='explore'),
    url(r'set/', views.SetView.as_view(), name='set'),
    url(r'expenditure/', views.Expenditure.as_view(), name='expenditure'),
    url(r'^(?P<country>\D+)/selection/$', views.selection, name='selection'),
    url(r'^(?P<country>\D+)/bar$', views.field, name='bar'),
    url(r'^(?P<country>\D+)/motion$', views.motion, name='motion'),
    url(r'^play/', views.play, name='play'),
    url(r'^week_selection/', views.week_selection, name='week_selection'),

    # (?P<fields>.+)
]

viz/models.py
from django.db import models


# Create your models here.

class BigTable(models.Model):
    srch_id = models.IntegerField(db_index=True)
    date_time = models.DateTimeField(db_index=True)
    site_id = models.IntegerField(db_index=True)
    visitor_location_country_id = models.IntegerField(blank=True, null=True, db_index=True)
    visitor_hist_starrating = models.FloatField(blank=True, null=True, db_index=True)
    visitor_hist_adr_usd = models.FloatField(blank=True, null=True, db_index=True)
    prop_country_id = models.IntegerField(db_index=True)
    prop_id = models.IntegerField(db_index=True)
    prop_starrating = models.IntegerField(db_index=True)
    prop_review_score = models.FloatField(blank=True, null=True, db_index=True)
    prop_brand_bool = models.BooleanField(db_index=True)
    prop_location_score1 = models.FloatField(blank=True, null=True, db_index=True)
    prop_location_score2 = models.FloatField(blank=True, null=True, db_index=True)
    prop_log_historical_price = models.FloatField(blank=True, null=True, db_index=True)
    position = models.IntegerField(db_index=True)
    price_usd = models.FloatField(blank=True, null=True, db_index=True)
    promotion_flag = models.BooleanField(db_index=True)
    srch_destination_id = models.IntegerField(db_index=True)
    srch_length_of_stay = models.IntegerField(db_index=True)
    srch_booking_window = models.IntegerField(db_index=True)
    srch_adults_count = models.IntegerField(db_index=True)
    srch_children_count = models.IntegerField(db_index=True)
    srch_room_count = models.IntegerField(db_index=True)
    srch_saturday_night_bool = models.BooleanField(db_index=True)
    srch_query_affinity_score = models.FloatField(blank=True, null=True, db_index=True)
    orig_destination_distance = models.FloatField(blank=True, null=True, db_index=True)
    random_bool = models.BooleanField(db_index=True)
    comp1_rate = models.IntegerField(blank=True, null=True, db_index=True)
    comp1_inv = models.IntegerField(blank=True, null=True, db_index=True)
    comp1_rate_percent_diff = models.FloatField(blank=True, null=True, db_index=True)
    comp2_rate = models.IntegerField(blank=True, null=True, db_index=True)
    comp2_inv = models.IntegerField(blank=True, null=True, db_index=True)
    comp2_rate_percent_diff = models.FloatField(blank=True, null=True, db_index=True)
    comp3_rate = models.IntegerField(blank=True, null=True, db_index=True)
    comp3_inv = models.IntegerField(blank=True, null=True, db_index=True)
    comp3_rate_percent_diff = models.FloatField(blank=True, null=True, db_index=True)
    comp4_rate = models.IntegerField(blank=True, null=True, db_index=True)
    comp4_inv = models.IntegerField(blank=True, null=True, db_index=True)
    comp4_rate_percent_diff = models.FloatField(blank=True, null=True, db_index=True)
    comp5_rate = models.IntegerField(blank=True, null=True, db_index=True)
    comp5_inv = models.IntegerField(blank=True, null=True, db_index=True)
    comp5_rate_percent_diff = models.FloatField(blank=True, null=True, db_index=True)
    comp6_rate = models.IntegerField(blank=True, null=True, db_index=True)
    comp6_inv = models.IntegerField(blank=True, null=True, db_index=True)
    comp6_rate_percent_diff = models.FloatField(blank=True, null=True, db_index=True)
    comp7_rate = models.IntegerField(blank=True, null=True, db_index=True)
    comp7_inv = models.IntegerField(blank=True, null=True, db_index=True)
    comp7_rate_percent_diff = models.FloatField(blank=True, null=True, db_index=True)
    comp8_rate = models.IntegerField(blank=True, null=True, db_index=True)
    comp8_inv = models.IntegerField(blank=True, null=True, db_index=True)
    comp8_rate_percent_diff = models.FloatField(blank=True, null=True, db_index=True)
    click_bool = models.BooleanField(db_index=True)
    gross_bookings_usd = models.FloatField(blank=True, null=True, db_index=True)
    booking_bool = models.BooleanField(db_index=True)


class Countries(models.Model):
    name = models.CharField(max_length=30, blank=True, null=True, db_index=True)
    a_name = models.CharField(max_length=40, blank=True, null=True, db_index=True)


class Continents(models.Model):
    name = models.CharField(max_length=30, blank=True, null=True, db_index=True)
    continent = models.CharField(max_length=50, blank=True, null=True, db_index=True)
    a_name = models.CharField(max_length=50, blank=True, null=True, db_index=True)

viz/views.py
import re
import json
import random
import datetime
import logging

from django.shortcuts import render, render_to_response
from django.views import generic
from django.db import connection

from django.http import Http404

from .forms import BarForm, MotionForm, WeekSelectionForm
from viz.models import Countries


# Data Types
numeric = ['visitor_hist_starrating', 'visitor_hist_adr_usd', 'prop_starrating',
           'prop_review_score',
           'prop_location_score1', 'prop_location_score2', 'prop_log_historical_price', 'price_usd',
           'srch_length_of_stay',
           'srch_booking_window', 'srch_adults_count', 'srch_children_count', 'srch_room_count',
           'srch_query_affinity_score',
           'orig_destination_distance', 'gross_bookings_usd']
identifiers = ['srch_id', 'site_id', 'visitor_location_country_id', 'prop_country_id', 'prop_id', 'position',
               'srch_destination_id']
booleans = ['prop_brand_bool', 'promotion_flag', 'srch_saturday_night_bool', 'random_bool', 'click_bool',
            'booking_bool']
filters = ['price_usd', 'visitor_hist_starrating', 'prop_starrating', 'prop_review_score']
competitor_info = ['comp1_rate', 'comp1_inv', 'comp1_rate_percent_diff', 'comp2_rate', 'comp2_inv',
                   'comp2_rate_percent_diff',
                   'comp3_rate', 'comp3_inv', 'comp3_rate_percent_diff', 'comp4_rate', 'comp4_inv',
                   'comp4_rate_percent_diff',
                   'comp5_rate', 'comp5_inv', 'comp5_rate_percent_diff', 'comp6_rate', 'comp6_inv',
                   'comp6_rate_percent_diff',
                   'comp7_rate', 'comp7_inv', 'comp7_rate_percent_diff', 'comp8_rate', 'comp8_inv',
                   'comp8_rate_percent_diff', ]


# Create your views here.
class HomeView(generic.TemplateView):
    template_name = "viz/index.html"


class ExploreView(generic.TemplateView):
    template_name = "viz/explore.html"


class SetView(generic.TemplateView):
    template_name = "viz/set.html"


class Expenditure(generic.TemplateView):
    template_name = "viz/expenditure.html"


def selection(request, country):
    return render_to_response('viz/selection.html', {"country": country})


# view that allows user to select fields that should be plotted for a graph
def field(request, country):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = BarForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # Determine what type of filter has been selected and its name
            filter_string = ""
            filter_type = ""
            filter_name = ""  # Only used if the filter is a numerical integer
            # Handle the case where the filter is a boolean type
            if form.cleaned_data['boolean_filters'] != '':
                filter_string = form.cleaned_data['boolean_filters']
                filter_type = "bool"
            # handle the case when the filter is either an integer or a float
            else:
                for f in filters:
                    if form.cleaned_data[f] is not None:
                        filter_string = form.cleaned_data[f]
                        if isinstance(filter_string, int):
                            filter_type = "int"
                            filter_name = f
                            break
                        else:
                            filter_type = "float"
                            break

            # Find country
            country = country.replace('_', ' ')
            country_object = Countries.objects.get(a_name=country)
            country_id = country_object.name

            # create query and render the graph
            columns = form.cleaned_data['fields']
            bar(columns, country_id, filter_string, filter_type, filter_name)

            return render_to_response('viz/bar.html')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = BarForm()

    return render(request, 'viz/filter_bar.html',
                  {'form': form, 'hotel_characteristics_loop': range(1, 9),
                   'visitor_information_loop': range(9, 13), 'srch_characteristics_loop': range(13, 23),
                   'booking_characteristics_loop': range(23, 26)})


def motion(request, country):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = MotionForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            if form.cleaned_data['name'] in identifiers:
                name = form.cleaned_data['name']
            else:
                raise Http404("Name is of the incorrect type")
            if form.cleaned_data['circum_color'] in numeric:
                circum_color = form.cleaned_data['circum_color']
            else:
                raise Http404("Circumference color is of the incorrect type")

            radius_val = form.cleaned_data['radius']
            y = form.cleaned_data['y']
            x = form.cleaned_data['x']

            # Find country
            country = country.replace('_', ' ')
            country_object = Countries.objects.get(a_name=country)
            country_id = country_object.name

            query = create_query_motion(name, circum_color, radius_val, y, x, country_id)
            collect_from_db_and_write_to_file(query)

            y_type = ""
            x_type = ""
            rad_type = ""
            # [{"xaxis":"Review Score", "yaxis":"User Rating", "xmax":"5","ymax":"20000", "ytype":"bool", "xtype":"num", "radType":"num"}]
            if y in numeric:
                y_type = "num"
            elif y in booleans:
                y_type = "bool"
            if x in numeric:
                x_type = "num"
            elif x in booleans:
                x_type = "bool"
            if radius_val in numeric:
                rad_type = "num"
            elif radius_val in booleans:
                rad_type = "bool"

            ymax = find_max_big_table(y, country_id)
            xmax = find_max_big_table(x, country_id)

            config = {"xaxis": x, "yaxis": y, "xmax": xmax, "ymax": ymax, "ytype": y_type, "xtype": x_type,
                      "radtype": rad_type, "radname":radius_val}
            write_config(config)

            # redirect to a new URL:
            return render_to_response('viz/motion.html')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = MotionForm(
            initial={'name': 'prop_id', 'x': 'visitor_hist_adr_usd', 'y': 'price_usd', 'radius': 'prop_starrating',
                     'circum_color': 'prop_review_score'})

    return render(request, 'viz/filter_motion.html', {'form': form})


def bar(fields, country, filter_string, filter_type, filter_name):
    if isinstance(fields, str):
        print(fields)
    field_string = re.sub("[\[\]\']", '', str(fields))
    columns = field_string.split(", ")

    # Bar charts should only be created for 1 column vs another
    if columns.__len__() != 2:
        raise Http404("There are more than two columns selected - A bar chart is not applicable to be created")

    graph_type = ""
    x = None
    y = None

    if columns[0] and columns[1] in numeric:
        graph_type = "numnum"
        x = columns[0]
        y = columns[1]
    elif columns[0] in numeric and columns[1] in identifiers:
        graph_type = "numnum"
        x = columns[1]
        y = columns[0]
    elif columns[0] in identifiers and columns[1] in numeric:
        graph_type = "numnum"
        x = columns[0]
        y = columns[1]
    elif columns[0] and columns[1] in identifiers:
        graph_type = "numnum"
        x = columns[0]
        y = columns[1]
    elif columns[0] in booleans and columns[1] in numeric:
        graph_type = "numbool"
        x = columns[1]
        y = columns[0]
    elif columns[0] in numeric and columns[1] in booleans:
        graph_type = "numbool"
        x = columns[0]
        y = columns[1]
    elif columns[0] in booleans and columns[1] in identifiers:
        graph_type = "numbool"
        x = columns[1]
        y = columns[0]
    elif columns[0] in identifiers and columns[1] in booleans:
        graph_type = "numbool"
        x = columns[0]
        y = columns[1]
    else:
        raise Http404("Could not determine graph type")

    query = create_query_bar(x, y, graph_type, country, filter_string, filter_type, filter_name)
    collect_from_db_and_write_to_file(query)

    config = {"xaxis": x, "yaxis": y, "type": graph_type}
    write_config(config)


def collect_from_db_and_write_to_file(query):
    cur = connection.cursor()
    cur.execute(query)
    db_columns = cur.fetchone()[0]

    if db_columns is None:
        raise Http404("There are no results matching the given parameters")

    with open("viz/static/viz/js/result.json", "w") as fp:
        json.dump(db_columns, fp)

    cur.close()
    connection.close()


def write_config(config):
    with open("viz/static/viz/js/config.json", "w") as fp:
        json.dump(config, fp)


def find_max_big_table(column, country):
    query = "SELECT MAX(" + column + ") FROM (SELECT " + column + " FROM viz_bigtable WHERE prop_country_id = " + country + ") t"

    cur = connection.cursor()
    cur.execute(query)
    maximum = cur.fetchone()[0]

    if maximum is None:
        raise Http404("Could not determine the max value for the column")
    else:
        return maximum


def create_query_motion(name, circum_color, radius_val, y, x, country):
    query = "SELECT array_to_json(array_agg(row_to_json(t))) AS id FROM (SELECT " + name + " as name, " + circum_color + \

viz/templates/viz/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="keyword" content="">
    <link rel="shortcut icon" href="">

    <title>Hotel Visualization - Selection</title>

    {% load staticfiles %}
    <!-- Bootstrap CSS -->
    <link href="{% static 'viz/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- bootstrap theme -->
    <link href="{% static 'viz/css/bootstrap-theme.css' %}" rel="stylesheet">
    <!-- font icon -->
    <link href="{% static 'viz/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet"/>
    <!-- Custom styles -->
    <link href="{% static 'viz/css/style.css' %}" rel="stylesheet">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
      <script src="js/respond.min.js"></script>
      <script src="js/lte-ie7.js"></script>
    <![endif]-->
</head>

<body>
<!-- container section start -->
<section id="container" class="">


    <header class="header dark-bg">
        <div class="toggle-nav">
            <div class="icon-reorder tooltips" data-original-title="Toggle Navigation" data-placement="bottom"></div>
        </div>

        <!--logo start-->
        <a href="{% url 'viz:index' %}" class="logo">Hotel <span class="lite">Visualization</span></a>
        <!--logo end-->
    </header>
    <!--header end-->

    <!--main content start-->
    <section id="main-content">
        <section class="wrapper">

            <div class="row">
                <!--Insert Content here-->
                <div class="col-lg-12">
                    <h2 align="center">How would you like to view the data?</h2>

                    <p><strong>The dataset consists of data obtained from an online travel agent. The data consists of
                        search
                        results between 2012 and 2013, there are ten million rows and 54 different columns. <br><br><br></strong>
                    </p>
                    <table style="width:100%">
                        <tr>
                            <td align="center" style="width: 40%" height="40%">
                                <a href="{% url 'viz:set' %}"> <img border="0" width="80%"
                                                                    alt="Explore"
                                                                    src="{% static 'viz/images/set.png' %}"/>
                                    <br> Go with the flow... </a>

                            </td>
                            <td align="center" style="width: 40%" height="40%">
                                <a href="{% url 'viz:explore' %}"> <img border="0" alt="Motion Graph" width="80%"
                                                                        src="{% static 'viz/images/explore.png' %}">
                                    <br>My
                                    Way or the High way...</a>


                            </td>
                        </tr>
                        <tr>
                            <td align="center" style="width: 40%">
                                <p><strong>This is the advanced search functionality provided by the website. It allows
                                    users to
                                    answer
                                    their own questions pertaining to the data set.</strong></p>
                            </td>
                            <td align="center" style="width: 40%">
                                <p><strong>This consists of graphs that the site designers and data analysts have deemed
                                    useful
                                    for viewing the data.</strong></p>
                            </td>
                        </tr>
                    </table>

                </div>
            </div>

            <!--Footer-->
            <footer>
                <div class="row">
                    <div class="col-lg-12">
                        <p>Copyright &copy; Hotel Visualization 2015</p>
                    </div>
                </div>
            </footer>

        </section>


    </section>
    <!--main content end-->
</section>

<!-- javascripts -->
<script src="{% static 'viz/js/jquery.js' %}"></script>
<!-- bootstrap -->
<script src="{% static 'viz/js/bootstrap.min.js' %}"></script>

<!-- nice scroll -->
<script src="{% static 'viz/js/jquery.scrollTo.min.js' %}"></script>
<script src="{% static 'viz/js/jquery.nicescroll.js' %}" type="text/javascript"></script>

<!--custom script for all page-->
<script src="{% static 'viz/js/scripts.js' %}"></script>

</body>
</html>

viz/templates/viz/selection.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="keyword" content="">
    <link rel="shortcut icon" href="">

    <title>Hotel Visualization - Selection</title>

    {% load staticfiles %}
    <!-- Bootstrap CSS -->
    <link href="{% static 'viz/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- bootstrap theme -->
    <link href="{% static 'viz/css/bootstrap-theme.css' %}" rel="stylesheet">
    <!-- font icon -->
    <link href="{% static 'viz/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet"/>
    <!-- Custom styles -->
    <link href="{% static 'viz/css/style.css' %}" rel="stylesheet">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
      <script src="js/respond.min.js"></script>
      <script src="js/lte-ie7.js"></script>
    <![endif]-->
</head>

<body>
<!-- container section start -->
<section id="container" class="">


    <header class="header dark-bg">
        <div class="toggle-nav">
            <div class="icon-reorder tooltips" data-original-title="Toggle Navigation" data-placement="bottom"></div>
        </div>

        <!--logo start-->
        <a href="{% url 'viz:index' %}" class="logo">Hotel <span class="lite">Visualization</span></a>
        <!--logo end-->
    </header>
    <!--header end-->

    <!--main content start-->
    <section id="main-content">
        <section class="wrapper">

            <div class="row">
                <!--Insert Content here-->
                <div class="col-lg-12">
                    <h1>Select a graph type...<br><br><br></h1>
                    <table style="width:100%">
                        <tr>
                            <td align="center" style="width: 50%">
                                <a href="{% url 'viz:bar' country %}"> <img border="0" alt="Bar Graph" width="80%"
                                                                            src="{% static 'viz/images/bar.PNG' %}">
                                    <br> Bar Graph </a>


                            </td>
                            <td align="center" style="width: 50%">
                                <a href="{% url 'viz:motion' country %}"> <img border="0" alt="Motion Graph" width="80%"
                                                                               src="{% static 'viz/images/motion.PNG' %}">
                                    <br> Motion Graph </a>


                            </td>
                        </tr>
                        <tr>
                            <td align="center" style="width: 50%">
                                <p><strong>This graph is useful to view two dimensions of data. Most of the data in the
                                    dataset can be viewed effectively by means of this type of chart.</strong></p>
                            </td>
                            <td align="center" style="width: 50%">
                                <p><strong>This graph is useful for viewing six dimensions of data. This allows users to
                                    ask complex questions that they may not necessarily have thought of
                                    initially</strong></p>
                            </td>
                        </tr>
                    </table>

                </div>
            </div>

            <!--Footer-->
            <footer>
                <div class="row">
                    <div class="col-lg-12">
                        <p>Copyright &copy; Hotel Visualization 2015</p>
                    </div>
                </div>
            </footer>

        </section>


    </section>
    <!--main content end-->
</section>

<!-- javascripts -->
<script src="{% static 'viz/js/jquery.js' %}"></script>
<!-- bootstrap -->
<script src="{% static 'viz/js/bootstrap.min.js' %}"></script>

<!-- nice scroll -->
<script src="{% static 'viz/js/jquery.scrollTo.min.js' %}"></script>
<script src="{% static 'viz/js/jquery.nicescroll.js' %}" type="text/javascript"></script>

<!--custom script for all page-->
<script src="{% static 'viz/js/scripts.js' %}"></script>

</body>
</html>

viz/templates/viz/set.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="keyword" content="">
    <link rel="shortcut icon" href="">

    <title>Hotel Visualization - Pre-determined Graph Selection</title>

    {% load staticfiles %}
    <!-- Bootstrap CSS -->
    <link href="{% static 'viz/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- bootstrap theme -->
    <link href="{% static 'viz/css/bootstrap-theme.css' %}" rel="stylesheet">
    <!-- font icon -->
    <link href="{% static 'viz/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet"/>
    <!-- Custom styles -->
    <link href="{% static 'viz/css/style.css' %}" rel="stylesheet">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
      <script src="js/respond.min.js"></script>
      <script src="js/lte-ie7.js"></script>
    <![endif]-->
</head>

<body>
<!-- container section start -->
<section id="container" class="">


    <header class="header dark-bg">
        <div class="toggle-nav">
            <div class="icon-reorder tooltips" data-original-title="Toggle Navigation" data-placement="bottom"></div>
        </div>

        <!--logo start-->
        <a href="{% url 'viz:index' %}" class="logo">Hotel <span class="lite">Visualization</span></a>
        <!--logo end-->
    </header>
    <!--header end-->

    <!--main content start-->
    <section id="main-content">
        <section class="wrapper">

            <div class="row">
                <div class="col-lg-12">
                    <h2>Select a graph that you would like to view... <br><br></h2>
                    <table style="width:100%">
                        <tr>
                            <td align="center" style="width:33%;height: 50%">
                                <a href="{% url 'viz:week_selection' %}?type=matrix"> <img border="0" alt="Matrix Graph"
                                                                                           style="padding: 5%"
                                                                                           width="100%"
                                                                                           src="{% static 'viz/images/matrix 2.png' %}">
                                    <br> Co-occurrence Matrix </a>


                            </td>
                            <td align="center" style="width:33%;height: 50%">
                                <a href="{% url 'viz:week_selection' %}?type=force"> <img border="0" alt="Force Graph"
                                                                                          width="100%"
                                                                                          style="padding: 5%"
                                                                                          src="{% static 'viz/images/force.png' %}">
                                    <br>Force Directed Graph</a>


                            </td>
                            <td align="center" style="width:33%;height: 50%">
                                <a href="{% url 'viz:expenditure' %}"> <img border="0" alt="Force Graph" width="100%"
                                                                            style="padding: 5%"
                                                                            src="{% static 'viz/images/budget_full.png' %}">
                                    <br> Expenditure Diagram </a>
                            </td>
                        </tr>
                        <tr>
                            <td align="center" style="width:33%">
                                <p><strong>This graph shows the country that the user has searched from verses
                                    the
                                    country that they wish to visit. This is useful in order to make
                                    observations regarding the popularity of the countries in the dataset.</strong></p>
                            </td>
                            <td align="center" style="width:33%">
                                <p><strong>This graph shows the connections between the country that the user has
                                    searched from verses the country they wish to visit. This is similar to the
                                    co-occurence matrix except it allows a user to better visualise the amount of times
                                    a particular search combination has occurred</strong></p>
                            </td>
                            <td align="center" style="width:33%">
                                <p><strong>A visual analytics tool to assist in understanding money spent on hotel
                                    bookings in countries around the world</strong></p>
                            </td>
                        </tr>
                    </table>

                </div>
            </div>

            <!-- Footer -->
            <footer>
                <div class="row">
                    <div class="col-lg-12">
                        <p>Copyright &copy; Hotel Visualization 2015</p>
                    </div>
                </div>
            </footer>

        </section>


    </section>
    <!--main content end-->
</section>
<!-- container section start -->

<!-- javascripts -->
<script src="{% static 'viz/js/jquery.js' %}"></script>
<!-- bootstrap -->
<script src="{% static 'viz/js/bootstrap.min.js' %}"></script>

<!-- nice scroll -->
<script src="{% static 'viz/js/jquery.scrollTo.min.js' %}"></script>
<script src="{% static 'viz/js/jquery.nicescroll.js' %}" type="text/javascript"></script>

<!--custom script for all page-->
<script src="{% static 'viz/js/scripts.js' %}"></script>

</body>
</html>